core/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from rest_framework.urlpatterns import format_suffix_patterns

from communication.views import ProductReviewComments
from core import views
from core.views import ProductListings

PRODUCT_LISTINGS = ProductListings.as_view(
    actions={'get': 'product_listings'})
GET_CATEGORIES = ProductListings.as_view(
    actions={'get': 'get_categories'})
GET_BRADS_N_COLORS = ProductListings.as_view(
    actions={'get': 'get_brands_n_colors'})
GET_PRODUCTS = ProductListings.as_view(
    actions={'get': 'get_products'})
PRODUCT_DETAIL = ProductListings.as_view(
    actions={'get': 'product_detail'})

app_name = "core"

# urlpatterns for web response
urlpatterns = [
    url(r'^product_listings', PRODUCT_LISTINGS, name='product_listings'),
    url(r'^get_products', GET_PRODUCTS, name='get_products'),
    url(r'^get_categories', GET_CATEGORIES, name='get_categories'),
    url(r'^get_brands_n_colors', GET_BRADS_N_COLORS,
        name='get_brands_n_colors'),
    url(r'^single_product/(?P<pk>\d+)/$', PRODUCT_DETAIL,
        name='single_product'),
    url(r'^product_detail/(?P<pk>\d+)/$', PRODUCT_DETAIL,
        name='product_detail'),
]
# urlpatterns for review comments

POST_REVIEW_ACTION = ProductReviewComments.as_view(
    actions={'post': 'post_review'})
POST_COMMENT_ACTION = ProductReviewComments.as_view(
    actions={'post': 'post_comment'})
POST_REPLY_ACTION = ProductReviewComments.as_view(
    actions={'post': 'post_reply'})

urlpatterns += [
    url(r'^post_review', csrf_exempt(POST_REVIEW_ACTION), name='post_review'),
    url(r'^post_comment', csrf_exempt(POST_COMMENT_ACTION), name='post_comment'),
    url(r'^post_reply', csrf_exempt(POST_REPLY_ACTION), name='post_reply')

]

urlpatterns += [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^about$', views.about, name='about'),
    url(r'^blog$', views.blog, name='blog'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^listings$', views.listings, name='listings'),
    url(r'^listings_single$', views.listings_single, name='listings_single'),
    url(r'^tracking$', views.tracking, name='tracking'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^cart$', views.cart, name='cart'),
    url(r'^confirmation$', views.confirmation, name='confirmation'),
    url(r'^elements$', views.elements, name='elements'),
    url(r'^single_blog$', views.single_blog, name='single_blog'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

donnyji/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path(r'graphql/',
                       csrf_exempt(GraphQLView.as_view(graphiql=True))),
                  path(r'', include('core.urls')),
                  path('', include('store.urls'))
              ] + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

core/models.py
# Create your models here.

core/views.py
from django.http import JsonResponse
from django.shortcuts import render
from account.models import User
from django.contrib import messages
from django.contrib.auth import login as user_login, logout as user_logout
from core.helpers import ProductListingsHelper
from django.contrib.auth.models import auth


def login(request):
    """
    login method
    :param request:
    :return:
    """
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'core/listed/listed/index.html')
        else:
            messages.info(request, 'invalid username or password')
    return render(request, 'core/winter/login.html')


def logout(request):
    """
    logout the user
    :param request:
    :return:
    """
    user_logout(request)
    return render(request, 'core/listed/listed/index.html')


def signup(request):
    """
    signup to user
    :param request:
    :return:
    """
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(username=username).exists():
            messages.error(request, 'username already exists')
            return render(request, 'core/winter/login.html')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'username already exists')
            return render(request, 'core/winter/login.html')
        else:
            user = User.objects.create_user(username=username, first_name=first_name,
                                            last_name=last_name, password=password, email=email)
            user.is_customer = True
            user.save()
            user_login(request, user)
            return render(request, 'core/listed/listed/index.html')
    return render(request, 'core/winter/login.html')


def index(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/listed/listed/index.html', context)


class ProductListings(ProductListingsHelper):
    """
    retrieve records for the product list page
    """

    def get_categories(self, request, format=None):
        """
        return hierarchy of categories
        :param request:
        :param format:
        :return:
        """
        categories = self.get_categories_gql(request=request,
                                             format=format)
        return JsonResponse(categories)

    def get_brands_n_colors(self, request, format=None):
        """
        return brands and colors on the given category
        :param request:
        :param format:
        :return:l
        """

        filters_dict = self.extract_filters(request=request)

        brands_obj = self.get_brands_gql(
            category_name=filters_dict.get("category_name"))
        colors_obj = self.get_colors_gql(
            category_name=filters_dict.get("category_name"))

        context = {'brands_obj': brands_obj,
                   "colors_obj": colors_obj}

        return render(request, 'core/winter/brand_side_bar.html', context)

    def product_listings(self, request, format=None):
        """
        return list of products, on given category name, brand name and
        color name etc
        :param request:
        :param format:
        :return:
        """

        categories = self.get_categories_gql(request=request,
                                             format=format)

        filters_dict = self.extract_filters(request=request)

        products_objs = self.get_products_gql(
            category_name=filters_dict.get("category_name"),
            brand_names=filters_dict.get("brand_names"),
            color_names=filters_dict.get("color_names"),
            min_price=filters_dict.get("min_price"),
            max_price=filters_dict.get("max_price"),
        )

        brands_obj = self.get_brands_gql(
            category_name=filters_dict.get("category_name"))
        colors_obj = self.get_colors_gql(
            category_name=filters_dict.get("category_name"))

        context = {'browse_categories': categories,
                   'brands_obj': brands_obj,
                   "browse_products": products_objs,
                   "colors_obj": colors_obj,
                   "category_name": filters_dict.get("category_name")}

        return render(request, 'core/winter/category.html', context)

    def get_products(self, request, format=None):
        """
        return products on the given brand, category and other filters
        :param request:
        :param format:
        :return:
        """

        filters_dict = self.extract_filters(request=request)

        products_objs = self.get_products_gql(
            category_name=filters_dict.get("category_name"),
            brand_names=filters_dict.get("brand_names"),
            color_names=filters_dict.get("color_names"),
            min_price=filters_dict.get("min_price"),
            max_price=filters_dict.get("max_price"),
        )

        context = {
            "browse_products": products_objs,
            "category_name": filters_dict.get("category_name")}

        return render(request, 'core/winter/products_listing.html', context)

    def product_detail(self, request, *args, **kwargs):
        """

        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        product_id = kwargs.get("pk")

        products_objs = self.get_products_gql(id=product_id)

        context = {
            "browse_products": products_objs[0]
        }

        return render(request, 'core/winter/single-product.html', context)


def about(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/about.html', context)


def contact(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/contact.html', context)


def listings(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/listed/listed/listings.html', context)


def category(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/category.html', context)


def listings_single(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/listed/listed/listings-single.html', context)


def tracking(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/tracking.html', context)


def checkout(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/checkout.html', context)


def cart(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/cart.html', context)


def confirmation(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/confirmation.html', context)


def elements(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/elements.html', context)


def blog(request):
    """

    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/blog.html', context)


def single_blog(request):
    """
    
    :param request:
    :return:
    """
    context = {'latest_question_list': "latest_question_list"}
    return render(request, 'core/winter/single-blog.html', context)

core/templates/core/winter/base.html
{% load static %}
<html lang="zxx">
{% block header_static %}
{% include "core/winter/head_statics.html" %}
{% endblock header_static%}

<body class="bg-white">

{% block header_part %}
<!--::header part start::-->
{% include "core/winter/header_parts.html" %}
<!-- Header part end-->
{% endblock header_part%}

{% block bread_crum %}
<!-- breadcrumb start-->
{% include "core/winter/bread_crum.html" %}
<!-- breadcrumb start-->
{% endblock bread_crum%}

{% block content %}
{% endblock content %}

{% block footer %}

{% csrf_token %}

{% include "core/winter/footer.html" %}

<script type="text/javascript">
    // using jQuery
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

</script>

{% endblock footer %}
</body>

</html>

core/templates/core/winter/brand_side_bar.html
{% load static %}
<div class="l_w_title">
    <h3>Product filters</h3>
</div>
<div class="widgets_inner">
    <div id="brand_widgets_inner">
        <ul class="list">
            <p>Brands</p>

            {% for brand in brands_obj %}
            <li>
                <input aria-label="checkbox button for following text input"
                       id="brand_side_bar" type="checkbox"
                       value="{{brand.brandName}}">
                {{brand}}
            </li>
            {% endfor %}

        </ul>
    </div>
    <div id="color_widgets_inner">
        <ul class="list">
            <p>color</p>
            {% for color_obj in colors_obj %}
            <li>
                <input aria-label="checkbox button for following text input"
                       id="color_side_bar" type="checkbox"
                       value="{{color_obj}}">
                {{color_obj}}
            </li>
            {% endfor %}

        </ul>
    </div>
</div>

core/templates/core/winter/bread_crum.html
<section class="breadcrumb breadcrumb_bg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <p>Home / About</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/core/winter/cart.html
{% extends "core/winter/base.html" %}
{% load static %}
{% block content %}

<!--================Cart Area =================-->
<section class="cart_area section_padding">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <div class="media">
                                <div class="d-flex">
                                    <img alt=""
                                         src="{% static 'core/winter/img/arrivel/arrivel_1.png' %}"/>
                                </div>
                                <div class="media-body">
                                    <p>Minimalistic shop for multipurpose
                                        use</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <h5>$360.00</h5>
                        </td>
                        <td>
                            <div class="product_count">
                                <!-- <input type="text" value="1" min="0" max="10" title="Quantity:"
                                  class="input-text qty input-number" />
                                <button
                                  class="increase input-number-increment items-count" type="button">
                                  <i class="ti-angle-up"></i>
                                </button>
                                <button
                                  class="reduced input-number-decrement items-count" type="button">
                                  <i class="ti-angle-down"></i>
                                </button> -->
                                <span class="input-number-decrement"> <i
                                        class="ti-minus"></i></span>
                                <input class="input-number" max="10"
                                       min="0" type="text" value="1">
                                <span class="input-number-increment"> <i
                                        class="ti-plus"></i></span>
                            </div>
                        </td>
                        <td>
                            <h5>$720.00</h5>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="media">
                                <div class="d-flex">
                                    <img alt=""
                                         src="{% static 'core/winter/img/arrivel/arrivel_2.png' %}"/>
                                </div>
                                <div class="media-body">
                                    <p>Minimalistic shop for multipurpose
                                        use</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <h5>$360.00</h5>
                        </td>
                        <td>
                            <div class="product_count">
                                <span class="input-number-decrement"> <i
                                        class="ti-minus"></i></span>
                                <input class="input-number" max="10"
                                       min="0" type="text" value="1">
                                <span class="input-number-increment"> <i
                                        class="ti-plus"></i></span>
                            </div>
                        </td>
                        <td>
                            <h5>$720.00</h5>
                        </td>
                    </tr>
                    <tr class="bottom_button">
                        <td>
                            <a class="btn_1" href="#">Update Cart</a>
                        </td>
                        <td></td>
                        <td></td>
                        <td>
                            <div class="cupon_text float-right">
                                <a class="btn_1" href="#">Close Coupon</a>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <h5>Subtotal</h5>
                        </td>
                        <td>
                            <h5>$2160.00</h5>
                        </td>
                    </tr>
                    <tr class="shipping_area">
                        <td></td>
                        <td></td>
                        <td>
                            <h5>Shipping</h5>
                        </td>
                        <td>
                            <div class="shipping_box">
                                <ul class="list">
                                    <li>
                                        Flat Rate: $5.00
                                        <input aria-label="Radio button for following text input"
                                               type="radio">
                                    </li>
                                    <li>
                                        Free Shipping
                                        <input aria-label="Radio button for following text input"
                                               type="radio">
                                    </li>
                                    <li>
                                        Flat Rate: $10.00
                                        <input aria-label="Radio button for following text input"
                                               type="radio">
                                    </li>
                                    <li class="active">
                                        Local Delivery: $2.00
                                        <input aria-label="Radio button for following text input"
                                               type="radio">
                                    </li>
                                </ul>
                                <h6>
                                    Calculate Shipping
                                    <i aria-hidden="true"
                                       class="fa fa-caret-down"></i>
                                </h6>
                                <select class="shipping_select">
                                    <option value="1">Bangladesh</option>
                                    <option value="2">India</option>
                                    <option value="4">Pakistan</option>
                                </select>
                                <select class="shipping_select section_bg">
                                    <option value="1">Select a State</option>
                                    <option value="2">Select a State</option>
                                    <option value="4">Select a State</option>
                                </select>
                                <input class="post_code" placeholder="Postcode/Zipcode"
                                       type="text"/>
                                <a class="btn_1" href="#">Update Details</a>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="checkout_btn_inner float-right">
                    <a class="btn_1" href="#">Continue Shopping</a>
                    <a class="btn_1 checkout_btn_1" href="#">Proceed to
                        checkout</a>
                </div>
            </div>
        </div>
</section>
<!--================End Cart Area =================-->
{% endblock content %}

core/templates/core/winter/login.html
{% extends "core/winter/base.html" %}
{% load static %}
{% block content %}
<!--================login_part Area =================-->
<div class="login-page">
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    {% else %}
                    {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
        {% endfor %}
    <div class="form">
        <form action="{% url 'core:signup' %}" method="POST" class="register-form">
            {% csrf_token %}
            <input type="text" placeholder="UserName" name="username"/>
            <input type="text" placeholder="FirstName" name="first_name"/>
            <input type="text" placeholder="LastName" name="last_name"/>
            <input type="text" placeholder="Email" name="email"/>
            <input type="password" placeholder="Password" name="password"/>
            <button>create</button>
            <p class="message">Already registered? <a href="#">Sign In</a></p>
        </form>
        <form action="{% url 'core:login' %}" method="POST" class="login-form">
            {% csrf_token %}
            <input type="text" placeholder="UserName" name="username"/>
            <input type="password" placeholder="Password" name="password"/>
            <button>login</button>
            <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>
    </div>
</div>
<!--================login_part end =================-->

<!-- subscribe_area part start-->
<section class="instagram_photo">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="instagram_photo_iner">
                    <div class="single_instgram_photo">
                        <img alt=""
                             src="{% static 'core/winter/img/instagram/inst_1.png' %}">
                        <a href="#"><i class="ti-instagram"></i></a>
                    </div>
                    <div class="single_instgram_photo">
                        <img alt=""
                             src="{% static 'core/winter/img/instagram/inst_2.png' %}">
                        <a href="#"><i class="ti-instagram"></i></a>
                    </div>
                    <div class="single_instgram_photo">
                        <img alt=""
                             src="{% static 'core/winter/img/instagram/inst_3.png' %}">
                        <a href="#"><i class="ti-instagram"></i></a>
                    </div>
                    <div class="single_instgram_photo">
                        <img alt=""
                             src="{% static 'core/winter/img/instagram/inst_4.png' %}">
                        <a href="#"><i class="ti-instagram"></i></a>
                    </div>
                    <div class="single_instgram_photo">
                        <img alt=""
                             src="{% static 'core/winter/img/instagram/inst_5.png' %}">
                        <a href="#"><i class="ti-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--::subscribe_area part end::-->
{% endblock content %}


core/templates/core/winter/price_range_side_bar.html
{% load static %}
<div class="l_w_title">
    <h3>Price Filter</h3>
</div>
<div class="widgets_inner">
    <div class="range_item" id="price_slider">
        <p>
            <input id="amount" readonly
                   style="border:0; color:#f6931f; font-weight:bold;"
                   type="text">
        </p>

        <div id="slider-range"></div>
    </div>
</div>

core/templates/core/winter/products_listing.html
{% load static %}

<div class="col-lg-12">
    <div class="product_top_bar d-flex justify-content-between align-items-center">
        <div class="single_product_menu product_bar_item">
            <h2>{{category_name}}
                ({{browse_products|length}})</h2>
        </div>
        <div class="product_top_bar_iner product_bar_item d-flex">
            <div class="product_bar_single">
                <select class="wide">
                    <option data-display="Default sorting">
                        Default sorting
                    </option>
                    <option value="1">Some option</option>
                    <option value="2">Another option
                    </option>
                    <option value="3">Potato</option>
                </select>
            </div>
            <div class="product_bar_single">
                <select>
                    <option data-display="Show 12">Show
                        12
                    </option>
                    <option value="1">Show 20</option>
                    <option value="2">Show 30</option>
                </select>
            </div>
        </div>
    </div>
</div>
{% for product in browse_products %}
<div class="col-lg-4 col-sm-6">
    <div class="single_category_product" id="single_category_product">
        <div class="single_category_img" id="single_category_img">
            <img id="category_img" alt=""
                 height="252" src="{{product.productImage.0.imageString}}"
                 width="42" prodid="{{product.id}}">
            <div class="category_social_icon">
                <ul>
                    <li><a href="#"><i
                            class="ti-heart"></i></a></li>
                    <li><a href="#"><i class="ti-bag"></i></a>
                    </li>
                </ul>
            </div>
            <div class="category_product_text" id="category_product_text" prodid="{{product.id}}">
                <a href="{% url 'core:product_detail' product.id %}"><h5>{{product.name}}</h5></a>
                <h5>actual price: ₹ {{product.actualPrice}}</h5>
                <p>sale price: ₹ {{product.salePrice}}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="col-lg-12 text-center">
    <a class="btn_2" href="#">More Items</a>
</div>

core/templates/core/winter/review_box.html
{% load static %}
<div class="review_box">
    <h4>Add a Review</h4>
    <div class='rating-stars text-center'>
        <p>Your Rating:</p>

        <ul class='list' id='stars'>
            <li class='star' data-value='1' title='Poor'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' data-value='2' title='Fair'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' data-value='3' title='Good'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' data-value='4' title='Excellent'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' data-value='5' title='WOW!!!'>
                <i class='fa fa-star fa-fw'></i>
            </li>
        </ul>
    </div>
    <form action="" class="row contact_form"
          id="form_add_review" method="post"
          novalidate="novalidate"> {% csrf_token %}
        <div class="col-md-12">
            <div class="form-group">
                <input autocomplete="off" class="form-control" id="rating"
                       name="rating"
                       placeholder="Your rating 1 to 5" type="hidden" value=""/>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <input class="form-control"
                       name="user_id"
                       placeholder="user id"
                       type="text" value="345"/>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea class="form-control"
                          name="message"
                          placeholder="Review"
                          rows="1"></textarea>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">

                <input class="form-control" id="product_id"
                       name="product_id" placeholder="product_id" type="hidden"
                       value={{browse_products.id}}>
            </div>
        </div>
        <div class="col-md-12 text-right">
            <button class="btn_3" id="button_add_review" type="submit"
                    value="submit">
                Submit Now
            </button>
        </div>
    </form>
</div>